In [1]:
import numpy as np 

base_folder = '/data/qgong/data/CICIDS2017'

x_feature_train = np.load(base_folder+'/X_train.npy')
y_label_train = np.load(base_folder+'/y_train.npy')

print(x_feature_train.shape, y_label_train.shape)
np.unique(y_label_train, return_counts=True)

(2260482, 76) (2260482,)


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1817232,  183889,  126994,  102390,    8253,    6362,    4766,
           4604,    4397,    1595]))

In [2]:
combined_data = np.hstack((x_feature_train, y_label_train.reshape(-1, 1)))
print(combined_data.shape)

(2260482, 77)


In [3]:
np.random.shuffle(combined_data)

In [4]:
from sklearn.model_selection import train_test_split

x = combined_data[:, :-1]
y = combined_data[:, -1]

# Step 5: Split into train, test, and validation sets
X_train, X_temp, y_train, y_temp = train_test_split(x, y, test_size=0.002, random_state=42)  # 98% train, 1% val, 1% test
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)  

print(X_train.shape, X_test.shape, X_val.shape, y_train.shape, y_test.shape, y_val.shape)

(2255961, 76) (2261, 76) (2260, 76) (2255961,) (2261,) (2260,)


In [5]:
import os 
import shutil

output_folder = base_folder+"/tab_ppdm_all_cicids2017"
if os.path.exists(output_folder):
        # If it exists, remove it
    shutil.rmtree(output_folder)
    print(f"Deleted Folder '{output_folder}' before creating!")

    
    # Create a new folder
os.makedirs(output_folder)
print(f"Folder '{output_folder}' has been created!")


Deleted Folder '/data/qgong/data/CICIDS2017/tab_ppdm_all_cicids2017' before creating!
Folder '/data/qgong/data/CICIDS2017/tab_ppdm_all_cicids2017' has been created!


In [6]:
np.save(output_folder+'/X_num_train.npy', X_train)
np.save(output_folder+'/y_train.npy', y_train)
np.save(output_folder+'/X_num_val.npy', X_val)
np.save(output_folder+'/y_val.npy', y_val)
np.save(output_folder+'/X_num_test.npy', X_test)
np.save(output_folder+'/y_test.npy', y_test)

Check generated data

In [5]:
import numpy as np 

x = np.load('/data/qgong/code/NID-GPT/exp/cicids2017_all/ddpm_cb/X_num_train.npy')
x_unnorm = np.load('/data/qgong/code/NID-GPT/exp/cicids2017_all/ddpm_cb/X_num_unnorm.npy')
y = np.load('/data/qgong/code/NID-GPT/exp/cicids2017_all/ddpm_cb/y_train.npy')


x.shape, x_unnorm.shape, y.shape

((2000000, 76), (2000000, 76), (2000000,))

In [8]:
print(x[0])
print(x_unnorm[0])

np.unique(y,return_counts=True)

[1.41666654e-07 4.55046005e-06 0.00000000e+00 9.30232558e-07
 0.00000000e+00 2.41740532e-04 2.58064516e-03 1.01022249e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 1.13207547e-01 4.16666667e-01 1.41666651e-07
 0.00000000e+00 1.41666651e-07 1.41666650e-07 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 1.33333320e-07
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 9.99855825e-01 9.94591933e-01 1.66666667e-01
 0.00000000e+00 4.14364641e-03 2.41740532e-04 1.79794521e-03
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 2.31164384e-03
 1.01022249e-03 0.00000000e+00 0.00000000e+00 0.00000000e+00
 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
 4.55046005e-06 9.32376446e-07 0.00000000e+00 0.00000000e+00
 3.84521484e-03 0.000000

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1607790,  162400,  112530,   90667,    7331,    5559,    4195,
           4110,    3961,    1457]))